all: pdi

pdi: main.cpp pdi.o 
	g++ --std=c++11 -Wall -Werror -Wpedantic -O3 pdi.o main.c -o pdi

pdi.o: lodepng.o pdi.h pdi.cpp
	g++ --std=c++11 -Wall -Werror -Wpedantic -O3 lodepng.o pdi.c -o pdi.o

lodepng.o: lodepng.h lodepng.cpp 
	g++ --std=c++11 -Wall -Werror -Wpedantic -O3 lodepng.cpp -o lodepng.o

clean:
rm -rf *.o *~ pdi